# Generated by Django 4.2.6 on 2023-10-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificate_jwt_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='jwt_token',
            new_name='jwt_token_access',
        ),
        migrations.AddField(
            model_name='certificate',
            name='jwt_token_refresh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
